<?xml version="1.0" encoding="UTF-8"?>
<wsdl:definitions targetNamespace="http://controller" xmlns:apachesoap="http://xml.apache.org/xml-soap" xmlns:impl="http://controller" xmlns:intf="http://controller" xmlns:wsdl="http://schemas.xmlsoap.org/wsdl/" xmlns:wsdlsoap="http://schemas.xmlsoap.org/wsdl/soap/" xmlns:xsd="http://www.w3.org/2001/XMLSchema">
<!--WSDL created by Apache Axis version: 1.4
Built on Apr 22, 2006 (06:55:48 PDT)-->
 <wsdl:types>
  <schema elementFormDefault="qualified" targetNamespace="http://controller" xmlns="http://www.w3.org/2001/XMLSchema">
   <element name="add">
    <complexType>
     <sequence>
      <element name="producttoadd" type="xsd:anyType"/>
     </sequence>
    </complexType>
   </element>
   <element name="addResponse">
    <complexType/>
   </element>
  </schema>
 </wsdl:types>

   <wsdl:message name="addRequest">

      <wsdl:part element="impl:add" name="parameters"/>

   </wsdl:message>

   <wsdl:message name="addResponse">

      <wsdl:part element="impl:addResponse" name="parameters"/>

   </wsdl:message>

   <wsdl:portType name="Server">

      <wsdl:operation name="add">

         <wsdl:input message="impl:addRequest" name="addRequest"/>

         <wsdl:output message="impl:addResponse" name="addResponse"/>

      </wsdl:operation>

   </wsdl:portType>

   <wsdl:binding name="ServerSoapBinding" type="impl:Server">

      <wsdlsoap:binding style="document" transport="http://schemas.xmlsoap.org/soap/http"/>

      <wsdl:operation name="add">

         <wsdlsoap:operation soapAction=""/>

         <wsdl:input name="addRequest">

            <wsdlsoap:body use="literal"/>

         </wsdl:input>

         <wsdl:output name="addResponse">

            <wsdlsoap:body use="literal"/>

         </wsdl:output>

      </wsdl:operation>

   </wsdl:binding>

   <wsdl:service name="ServerService">

      <wsdl:port binding="impl:ServerSoapBinding" name="Server">

         <wsdlsoap:address location="http://localhost:8084/WebImplement/services/Server"/>

      </wsdl:port>

   </wsdl:service>

</wsdl:definitions>
